title: Gaurav Bokil # your name (or website title) here
logo: "/images/myphoto.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm passionate about pushing the limits of computational modelling and simulation through numerical methods, optimization, deep learning and extensive research.
  <br><br>
  <a href = "/pdf/GauravBokil.pdf">Resume</a><br><br>
  Personal email:
  <a href = "mailto: gauravbokil8@gmail.com">gauravbokil8@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/gauravbokil8/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
